### ISSUE TITLE
下载下来，下载好netutils之后，编译报下面的错误

### ISSUE THREAD

**Issue by linhuikui** [flyingcys/w600#1]
Libraries\Include\wm_regs.h(75): error:  #5: cannot open source input file "core_cm3.h": No such file or directory

**Comment by linhuikui** [comment]
头文件路径加入之后，编译时报链接错误(40个)，找不到相应库文件：
.\build\rtthread-w600.axf: Error: L6218E: Undefined symbol tls_ethernet_data_rx_callback (referred from drv_wifi.o).
.\build\rtthread-w600.axf: Error: L6218E: Undefined symbol tls_wifi_buffer_acquire (referred from drv_wifi.o).

**Comment by flyingcys** [comment]
重新更新下代码，记得用env执行下scons --target=mdk4 -s

**Comment by linhuikui** [comment]
core_cm3.h这个头文件路径，在工程中没有加入，编译时找不到

**Comment by flyingcys** [comment]
mdk5工程已经更新，使用scons --target=mdk5 -s就可以解决
